### ISSUE TITLE
Athena stack

### ISSUE THREAD

**Issue by DraTeots** [eic/eic-spack#116]
Install ATHENA stack via spack. Would be nice to have as it would allow native debugging + native graphics support. + it would allow maybe to compile with QT and have QT event display etc.

**Comment by DraTeots** [comment]
Spack evnironment

https://eicweb.phy.anl.gov/containers/eic_container/-/blob/master/spack.yaml

**Comment by DraTeots** [comment]
Some modified packages

https://eicweb.phy.anl.gov/containers/eic_container/-/tree/master/spack/packages

**Comment by wdconinc** [comment]
Accidentally committed right into master... https://github.com/eic/eic-spack/commit/a78eb6d390ba6396cccdb4899160cb4f2769572d
