### ISSUE TITLE
dire linker flag issue

### ISSUE THREAD

**Issue by wdconinc** [eic/eic-spack#12]
Patch is implemented in our dire/package.py but tracking here and at https://gitlab.com/wdconinc/direforpythia/-/merge_requests/1.

There appears to be no upstream repository, so sent by email to Stefan Prestel at Lund.

**Comment by wdconinc** [comment]
@mdiefent Do you know how to get patches to the dire developers? See link above.

**Comment by wdconinc** [comment]
Maybe we can pin down Stefan on Monday August 17 Pythia 8 by Stefan Prestel (LUND). I will try to attend, but I have to give an EIC talk at the TRIUMF science week that day.

**Comment by mdiefent** [comment]
@wdconinc I have sent the email to the developers, Stefan Hoeche (FNAL) and Stefan Prestel (LUND).

**Comment by wdconinc** [comment]
Probably a WONTFIX. Dealt with upstream. Largely obsolete for newer pythia8.
