### ISSUE TITLE
Add maintainers to all packages

### ISSUE THREAD

**Issue by wdconinc** [eic/eic-spack#2]
Currently there are no maintainers. As the number of packages grows, we should add maintainers who have authority over issues and pull requests related to those packages.

**Comment by wdconinc** [comment]
- [ ] aida
- [ ] dd4hep
- [ ] delphes
- [ ] dire
- [ ] eicroot
- [ ] eic-smear
- [ ] ejana
- [ ] escalate
- [ ] fastjet
- [ ] fun4all
- [ ] g4e
- [ ] gaudi
- [ ] geant3-vmc
- [ ] geant4-vmc
- [ ] genfit
- [ ] hepmc3
- [ ] jana2
- [ ] lcov
- [ ] lhapdf
- [ ] lhapdf5
- [ ] mysql
- [ ] podio
- [ ] py-pyminuit2
- [ ] py-qmtest
- [ ] pythia6
- [ ] pythia8
- [ ] rapgap
- [ ] tricktrack
- [ ] vgm
- [ ] vmc
- [ ]

**Comment by mdiefent** [comment]
I will maintain DIRE, HepMC3, LHAPDF, and Pythia8 and ask the developers for input about Spack packages (which will be useful not only for EIC).

**Comment by wdconinc** [comment]
Ha, you are too quick. I accidentally copied some package that are already in spack upstream. I was editing but since you were clicking the checkboxes, I got a conflict.

In any case, these are already available upstream: hepmc3, lhapdf (not lhapdf5), pythia8.

**Comment by wdconinc** [comment]
I have now removed the ones that already have a maintainer from the list above.

**Comment by wdconinc** [comment]
Removed packages now in upstream with maintainer.
