### ISSUE TITLE
dd4hep: ion patch uses unstable link

### ISSUE THREAD

**Issue by wdconinc** [eic/eic-spack#393]
n/t

**Comment by wdconinc** [comment]
Something like https://github.com/AIDASoft/DD4hep/compare/263f61fc5cf4a4ea1cc09abd67ba9a076568601c..c71dfab8cb2993d31cd39b6b167fc55e70ef240e.patch?full_index=1

**Comment by kkauder** [comment]
The Additional Information links only go back to here, i.e. they translate to `[spack-build-out.txt](https://github.com/eic/eic-spack/issues/393)`

**Comment by wdconinc** [comment]
I was lazy and didn't complete the template :-) I was so lazy that I didn't even remove the template :-)

**Comment by kkauder** [comment]
:D Understood

**Comment by wdconinc** [comment]
Fixed in #394
