### ISSUE TITLE
Add to spack-repo topic

### ISSUE THREAD

**Issue by DraTeots** [eic/eic-spack#92]
We should add this repo to spack-repo topic, possibly other eic-spack related repos to other spack topics

https://github.com/search?q=spack&type=topics

https://github.com/topics/spack-repo

https://github.com/topics/spack-packages

It is not only convenient for searching this repo through github, but also it is relevant for google search. At least that is how I stumbled into these topics.

**Comment by wdconinc** [comment]
Done.
